language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - django-admin makemigrations
  - django-admin migrate

script:
  - pytest --cov=apps/

after_success:
  - coveralls