language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - psql -c 'create database questioner;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - pytest --cov=apps/

after_success:
  - coveralls