# Generated by Django 2.2 on 2019-04-28 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetup', '0002_auto_20190428_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesmodel',
            name='for_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetup.QuestionModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votesmodel',
            name='vote',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votesmodel',
            name='voter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
