# Generated by Django 2.2 on 2019-04-29 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetup', '0003_auto_20190428_1649'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votesmodel',
            unique_together={('voter', 'for_question')},
        ),
    ]
